services:
  php:
    restart: unless-stopped
    build: ./docker/php-fmp
    volumes:
      - ${APP_WEB_PATH}:/var/www/html
    links:
      - mysql
  mysql:
    image: mariadb:10.11
    restart: unless-stopped
    volumes:
      - ${DATA_PATH}/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
  nginx:
    image: nginx:latest
    ports:
      - ${NGINX_WEB_PORT}:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
